### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by sispus** [IngoMeyer441/radiotray-ng-mpris#3]
Hi,
It won't start.

```
❯ radiotray-ng-mpris
Traceback (most recent call last):
  File "/usr/bin/radiotray-ng-mpris", line 33, in <module>
    sys.exit(load_entry_point('radiotray-ng-mpris==0.1.1', 'console_scripts', 'radiotray-ng-mpris')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/radiotray-ng-mpris", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/radiotray_ng_mpris/cli.py", line 18, in <module>
    from .wrap import setup_signal_handling, wrap_radiotray_ng
  File "/usr/lib/python3.11/site-packages/radiotray_ng_mpris/wrap.py", line 14, in <module>
    from mpris_server import Metadata, MetadataObj
  File "/usr/lib/python3.11/site-packages/mpris_server/__init__.py", line 5, in <module>
    from . import adapters, base, interfaces, mpris, server, types
  File "/usr/lib/python3.11/site-packages/mpris_server/adapters.py", line 6, in <module>
    from .base import ActivePlaylist, DEFAULT_DESKTOP, DEFAULT_ORDERINGS, DEFAULT_PLAYLIST_COUNT, DEFAULT_RATE, DbusObj, \
  File "/usr/lib/python3.11/site-packages/mpris_server/base.py", line 27
    type Properties = Collection[Property]
         ^^^^^^^^^^
SyntaxError: invalid syntax

```

**Comment by IngoMeyer441** [comment]
Hi, thanks for your report. Do you use Manjaro Linux? On Manjaro, the dependency `python-mpris_server` is broken, because it requires Python 3.12, but Manjaro still uses Python 3.11.

What you can do:

- Wait until Python is upgraded (should happen in the next weeks)
- Downgrade `mpris_server` to the previous AUR version `0.4.2`.
